name: Auto assign reviewer

on:
  pull_request:
    types: [opened]

jobs:
  assign:
    runs-on: ubuntu-latest

    steps:
      - name: Assign reviewer
        uses: actions-ecosystem/action-add-reviewer@v1
        with:
          reviewers: 'Schnee'
